/*
 * This source file was generated by the Gradle 'init' task
 */
package io.dave.matrix;

import org.junit.Test;
import static org.junit.Assert.*;

public class Matrix {
    @Test public void someLibraryMethodReturnsTrue() {
        Matrix classUnderTest = new Matrix();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
